# Generated by Django 5.0.4 on 2024-04-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_fk_id', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('time_stamp', models.DateTimeField()),
                ('sts', models.DateTimeField()),
                ('speed', models.IntegerField()),
            ],
        ),
    ]
